/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingsRouteImport } from './routes/weddings'
import { Route as WeddingPlannerKanpurRouteImport } from './routes/wedding-planner-kanpur'
import { Route as WeddingPhotographyKanpurRouteImport } from './routes/wedding-photography-kanpur'
import { Route as WeddingDecorationKanpurRouteImport } from './routes/wedding-decoration-kanpur'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PreWeddingPhotographyKanpurRouteImport } from './routes/pre-wedding-photography-kanpur'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EventPlannerKanpurRouteImport } from './routes/event-planner-kanpur'
import { Route as CorporateEventManagementKanpurRouteImport } from './routes/corporate-event-management-kanpur'
import { Route as BirthdayEventPlannerKanpurRouteImport } from './routes/birthday-event-planner-kanpur'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const WeddingsRoute = WeddingsRouteImport.update({
  id: '/weddings',
  path: '/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingPlannerKanpurRoute = WeddingPlannerKanpurRouteImport.update({
  id: '/wedding-planner-kanpur',
  path: '/wedding-planner-kanpur',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingPhotographyKanpurRoute =
  WeddingPhotographyKanpurRouteImport.update({
    id: '/wedding-photography-kanpur',
    path: '/wedding-photography-kanpur',
    getParentRoute: () => rootRouteImport,
  } as any)
const WeddingDecorationKanpurRoute = WeddingDecorationKanpurRouteImport.update({
  id: '/wedding-decoration-kanpur',
  path: '/wedding-decoration-kanpur',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PreWeddingPhotographyKanpurRoute =
  PreWeddingPhotographyKanpurRouteImport.update({
    id: '/pre-wedding-photography-kanpur',
    path: '/pre-wedding-photography-kanpur',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EventPlannerKanpurRoute = EventPlannerKanpurRouteImport.update({
  id: '/event-planner-kanpur',
  path: '/event-planner-kanpur',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateEventManagementKanpurRoute =
  CorporateEventManagementKanpurRouteImport.update({
    id: '/corporate-event-management-kanpur',
    path: '/corporate-event-management-kanpur',
    getParentRoute: () => rootRouteImport,
  } as any)
const BirthdayEventPlannerKanpurRoute =
  BirthdayEventPlannerKanpurRouteImport.update({
    id: '/birthday-event-planner-kanpur',
    path: '/birthday-event-planner-kanpur',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/birthday-event-planner-kanpur': typeof BirthdayEventPlannerKanpurRoute
  '/corporate-event-management-kanpur': typeof CorporateEventManagementKanpurRoute
  '/event-planner-kanpur': typeof EventPlannerKanpurRoute
  '/events': typeof EventsRoute
  '/pre-wedding-photography-kanpur': typeof PreWeddingPhotographyKanpurRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding-decoration-kanpur': typeof WeddingDecorationKanpurRoute
  '/wedding-photography-kanpur': typeof WeddingPhotographyKanpurRoute
  '/wedding-planner-kanpur': typeof WeddingPlannerKanpurRoute
  '/weddings': typeof WeddingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/birthday-event-planner-kanpur': typeof BirthdayEventPlannerKanpurRoute
  '/corporate-event-management-kanpur': typeof CorporateEventManagementKanpurRoute
  '/event-planner-kanpur': typeof EventPlannerKanpurRoute
  '/events': typeof EventsRoute
  '/pre-wedding-photography-kanpur': typeof PreWeddingPhotographyKanpurRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding-decoration-kanpur': typeof WeddingDecorationKanpurRoute
  '/wedding-photography-kanpur': typeof WeddingPhotographyKanpurRoute
  '/wedding-planner-kanpur': typeof WeddingPlannerKanpurRoute
  '/weddings': typeof WeddingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/birthday-event-planner-kanpur': typeof BirthdayEventPlannerKanpurRoute
  '/corporate-event-management-kanpur': typeof CorporateEventManagementKanpurRoute
  '/event-planner-kanpur': typeof EventPlannerKanpurRoute
  '/events': typeof EventsRoute
  '/pre-wedding-photography-kanpur': typeof PreWeddingPhotographyKanpurRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding-decoration-kanpur': typeof WeddingDecorationKanpurRoute
  '/wedding-photography-kanpur': typeof WeddingPhotographyKanpurRoute
  '/wedding-planner-kanpur': typeof WeddingPlannerKanpurRoute
  '/weddings': typeof WeddingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/birthday-event-planner-kanpur'
    | '/corporate-event-management-kanpur'
    | '/event-planner-kanpur'
    | '/events'
    | '/pre-wedding-photography-kanpur'
    | '/sitemap.xml'
    | '/wedding-decoration-kanpur'
    | '/wedding-photography-kanpur'
    | '/wedding-planner-kanpur'
    | '/weddings'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/birthday-event-planner-kanpur'
    | '/corporate-event-management-kanpur'
    | '/event-planner-kanpur'
    | '/events'
    | '/pre-wedding-photography-kanpur'
    | '/sitemap.xml'
    | '/wedding-decoration-kanpur'
    | '/wedding-photography-kanpur'
    | '/wedding-planner-kanpur'
    | '/weddings'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/birthday-event-planner-kanpur'
    | '/corporate-event-management-kanpur'
    | '/event-planner-kanpur'
    | '/events'
    | '/pre-wedding-photography-kanpur'
    | '/sitemap.xml'
    | '/wedding-decoration-kanpur'
    | '/wedding-photography-kanpur'
    | '/wedding-planner-kanpur'
    | '/weddings'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BirthdayEventPlannerKanpurRoute: typeof BirthdayEventPlannerKanpurRoute
  CorporateEventManagementKanpurRoute: typeof CorporateEventManagementKanpurRoute
  EventPlannerKanpurRoute: typeof EventPlannerKanpurRoute
  EventsRoute: typeof EventsRoute
  PreWeddingPhotographyKanpurRoute: typeof PreWeddingPhotographyKanpurRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WeddingDecorationKanpurRoute: typeof WeddingDecorationKanpurRoute
  WeddingPhotographyKanpurRoute: typeof WeddingPhotographyKanpurRoute
  WeddingPlannerKanpurRoute: typeof WeddingPlannerKanpurRoute
  WeddingsRoute: typeof WeddingsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weddings': {
      id: '/weddings'
      path: '/weddings'
      fullPath: '/weddings'
      preLoaderRoute: typeof WeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-planner-kanpur': {
      id: '/wedding-planner-kanpur'
      path: '/wedding-planner-kanpur'
      fullPath: '/wedding-planner-kanpur'
      preLoaderRoute: typeof WeddingPlannerKanpurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-photography-kanpur': {
      id: '/wedding-photography-kanpur'
      path: '/wedding-photography-kanpur'
      fullPath: '/wedding-photography-kanpur'
      preLoaderRoute: typeof WeddingPhotographyKanpurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-decoration-kanpur': {
      id: '/wedding-decoration-kanpur'
      path: '/wedding-decoration-kanpur'
      fullPath: '/wedding-decoration-kanpur'
      preLoaderRoute: typeof WeddingDecorationKanpurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-wedding-photography-kanpur': {
      id: '/pre-wedding-photography-kanpur'
      path: '/pre-wedding-photography-kanpur'
      fullPath: '/pre-wedding-photography-kanpur'
      preLoaderRoute: typeof PreWeddingPhotographyKanpurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-planner-kanpur': {
      id: '/event-planner-kanpur'
      path: '/event-planner-kanpur'
      fullPath: '/event-planner-kanpur'
      preLoaderRoute: typeof EventPlannerKanpurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-event-management-kanpur': {
      id: '/corporate-event-management-kanpur'
      path: '/corporate-event-management-kanpur'
      fullPath: '/corporate-event-management-kanpur'
      preLoaderRoute: typeof CorporateEventManagementKanpurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthday-event-planner-kanpur': {
      id: '/birthday-event-planner-kanpur'
      path: '/birthday-event-planner-kanpur'
      fullPath: '/birthday-event-planner-kanpur'
      preLoaderRoute: typeof BirthdayEventPlannerKanpurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BirthdayEventPlannerKanpurRoute: BirthdayEventPlannerKanpurRoute,
  CorporateEventManagementKanpurRoute: CorporateEventManagementKanpurRoute,
  EventPlannerKanpurRoute: EventPlannerKanpurRoute,
  EventsRoute: EventsRoute,
  PreWeddingPhotographyKanpurRoute: PreWeddingPhotographyKanpurRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WeddingDecorationKanpurRoute: WeddingDecorationKanpurRoute,
  WeddingPhotographyKanpurRoute: WeddingPhotographyKanpurRoute,
  WeddingPlannerKanpurRoute: WeddingPlannerKanpurRoute,
  WeddingsRoute: WeddingsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
